import time

print('Olá, Guerreiro! Seja muito Bem Vindo a este desafio!')
time.sleep(1.4)
print('Para iniciarmos sua missão, eu preciso saber o seu nome.')
nome = input('Como você se chama?')
time.sleep(1.4)
print('Você realmente esta preparado?')
input('Sim ou não?')
time.sleep(1.4)
print('Muito bom!', nome, '.Seu desafio começa agora!')
time.sleep(1.4)
print('E a sua missão é derrotar o poderoso Black Dragon!')

time.sleep(2)
# VIDA DO DRAGÃO
vd = int(2000)
# VIDA DO GUERREIRO
vg = int(200)
# ATAQUE DO DRAGÃO
atkd = int(100)
# ATAQUE DO GUERREIRO
atkg = int(500)
# DEFESA DO GUERREIRO
df = int(50)
vd = (vd - atkg)

time.sleep(1.4)
print('>>', nome, 'ATACA  <<')
time.sleep(1.4)
print('A vida dele é de:', vd)
time.sleep(1.4)
print('>> BLACK DRAGON ATACA <<')
time.sleep(1.4)
pd = (atkd - df)
vg = (vg - pd)
print('Golpe forte.. a sua vida cai para:', vg)
time.sleep(1.4)
vd = (vd - atkg)
vd = (vd - atkg)
print(nome, 'CORRE EM DIREÇÃO AO BLACK DRAGON PARA REALIZAR UM ATAQUE DUPLO!')
time.sleep(1.4)
print(nome, 'ACERTA EM CHEIO O ALVO!')
time.sleep(1.4)
print('A vida dele é de:', vd)
time.sleep(1.4)
print('>> BLACK DRAGON ATACA NOVAMENTE <<')
time.sleep(1.4)
pd = (atkd - df)
vg = (vg - pd)
print('Golpe crítico.. a sua vida cai para:', vg)
time.sleep(1.4)
vd = (vd - atkg)
print(nome, 'TEM A SUA ULTIMA CHANCE')
time.sleep(1.4)
print('ELE ACERTA UM GOLPE FATAL CORTANDO A CABEÇA DO BLACK DRAGON')
time.sleep(1.4)
print('A vida do Black Dragon cai para', vd)
time.sleep(1.4)
print('BLACK DRAGON CAI MORTO!')
time.sleep(2)
print(f'PARABÉNS GRANDE GUERREIRO{nome}. VOCÊ DERROTOU O DRAGÃO E CONCLUIU SUA MISSÃO!')
print('Retomando testes e estudos com Python')
